[linters]
disable-all = true
enable = [
  "asasalint",
  "asciicheck",
  "bidichk",
  "bodyclose",
  "containedctx",
  "contextcheck",
  "decorder",
  "depguard",
  "dogsled",
  "dupl",
  "dupword",
  "durationcheck",
  "errcheck",
  "errchkjson",
  "errname",
  "errorlint",
  "execinquery",
  "exhaustive",
  "exportloopref",
  "forbidigo",
  "gci",
  "ginkgolinter",
  "gocheckcompilerdirectives",
  "gochecknoglobals",
  "gochecknoinits",
  "gocognit",
  "goconst",
  "gocritic",
  "godot",
  "godox",
  "goerr113",
  "gofmt",
  "gofumpt",
  "goheader",
  "goimports",
  "gomoddirectives",
  "gomodguard",
  "goprintffuncname",
  "gosec",
  "gosimple",
  "gosmopolitan",
  "govet",
  "grouper",
  "importas",
  "ineffassign",
  "interfacebloat",
  "ireturn",
  "lll",
  "loggercheck",
  "maintidx",
  "makezero",
  "mirror",
  "misspell",
  "musttag",
  "nakedret",
  "nestif",
  "nilerr",
  "nilnil",
  "noctx",
  "nolintlint",
  "nonamedreturns",
  "nosprintfhostport",
  "prealloc",
  "predeclared",
  "promlinter",
  "reassign",
  "revive",
  "rowserrcheck",
  "sqlclosecheck",
  "staticcheck",
  "stylecheck",
  "tagalign",
  "tagliatelle",
  "tenv",
  "testableexamples",
  "thelper",
  "tparallel",
  "unconvert",
  "unparam",
  "unused",
  "usestdlibvars",
  "wastedassign",
  "whitespace",
  "wrapcheck",
  "zerologlint",
]

# Disable some linters on test files.
[[issues.exclude-rules]]
path = "_test\\.go"
linters = [
  "goerr113",
  "ireturn",
  "wrapcheck",
]

[[linters-settings.revive.rules]]
name = "exported"
arguments = ["disableStutteringCheck"]
